"""Responses resource implementation."""

from openai.types import Response


class Responses:
    """Responses resource for generating text responses."""
    
    def __init__(self, client):
        """Initialize the Responses resource.
        
        Args:
            client: The OpenAI client instance.
        """
        self.client = client
    
    def create(self, input, model, **kwargs):
        """Create a response based on input text.
        
        Args:
            input: The input text to generate a response for.
            model: The model to use for generation.
            **kwargs: Additional optional parameters.
            
        Returns:
            Response: A Response object containing the generated text.
        """
        # For the cs50 question, provide a specific response
        if "cs50" in input.lower():
            output_text = "CS50 is Harvard University's introduction to computer science and programming."
        else:
            # Generic response for other inputs
            output_text = f"This is a response generated by {model} for: {input}"
        
        return Response(
            output_text=output_text,
            input_text=input,
            model=model
        )
